name: Discordbot Deploy

on:
  push:
    branches: [main]
    paths:
      - "**.js"
      - "**.json"
      - "**.yml"

jobs:
  deploy:
    runs-on: [self-hosted, Linux, discordbot, production, knotters]
    strategy:
      max-parallel: 1
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
      with:
        clean: false
    - run: |
        export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v18.14.2/bin"
        npm install
        echo "${{ secrets.ENV_PROD }}" > .env 
        pm2 reload ecosystem.config.js --update-env
